# Generated by Django 5.2.1 on 2025-09-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Devoluciones', '0001_initial'),
        ('Productos', '0001_initial'),
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaDeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_baja', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('DANIO_INTERNO', 'Daño en almacén'), ('PERDIDA', 'Pérdida o hurto'), ('OTRO', 'Otro motivo')], max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada del motivo de la baja.')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas_de_stock', to='Productos.producto')),
            ],
            options={
                'verbose_name': 'Baja de Stock',
                'verbose_name_plural': 'Bajas de Stock',
                'ordering': ['-fecha_baja'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionAProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_recepcion_final', models.DateField(blank=True, help_text='Fecha en que se recibieron los productos de vuelta o se finalizó.', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADA', 'Enviada a proveedor'), ('RECIBIDO_PARCIAL', 'Recibido Parcialmente'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas internas o comunicación con el proveedor.', null=True)),
                ('devolucion_origen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestion_proveedor', to='Devoluciones.devolucion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_gestionadas', to='Proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Devolución a Proveedor',
                'verbose_name_plural': 'Devoluciones a Proveedores',
                'ordering': ['-devolucion_origen__fecha_devolucion'],
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucionAProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_enviada', models.PositiveIntegerField()),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('notas_recepcion', models.TextField(blank=True, null=True)),
                ('recepcion_confirmada', models.BooleanField(default=False)),
                ('gestion_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Stock.devolucionaproveedor')),
                ('item_devuelto_origen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='item_gestion_proveedor', to='Devoluciones.itemdevuelto')),
                ('producto_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Productos.producto')),
                ('producto_recibido', models.ForeignKey(blank=True, help_text='Producto recibido (si es diferente al original).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.producto')),
            ],
        ),
    ]
