# Generated by Django 5.2.1 on 2025-09-24 18:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Creditos', '0001_initial'),
        ('Pedidos', '0001_initial'),
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de venta')),
                ('metodo_entrega', models.CharField(choices=[('domicilio', 'Domicilio'), ('tienda', 'Reclama en Tienda')], default='tienda', max_length=20, verbose_name='Método de Entrega')),
                ('direccion_entrega', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monto_cubierto_con_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monto_pago_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('metodo_pago_adicional', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], max_length=50, null=True)),
                ('comprobante_pago_adicional', models.FileField(blank=True, null=True, upload_to='comprobantes_pago_adicional/')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20)),
                ('tiene_devolucion', models.BooleanField(default=False, verbose_name='¿Tiene Devoluciones?')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_registro', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='Clientes.cliente')),
                ('credito_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_asociadas', to='Creditos.credito')),
                ('pedido_origen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='Pedidos.pedido', verbose_name='Pedido de Origen')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre_historico', models.CharField(max_length=200)),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario_historico', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
