# Generated by Django 5.2.1 on 2025-08-31 02:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Creditos', '0001_initial'),
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='comprobantes/', verbose_name='Imagen del Comprobante')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('monto_verificado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Verificado')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario en el Momento de la Compra')),
                ('producto', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token_seguimiento', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email_invitado', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Invitado')),
                ('tipo_documento_invitado', models.CharField(blank=True, max_length=3, null=True)),
                ('documento_invitado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('pendiente_pago_temporal', 'Pendiente de Pago (1h)'), ('en_verificacion', 'En Verificación de Pago'), ('pago_incompleto', 'Pago Incompleto'), ('confirmado', 'Confirmado y en Preparación'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('cancelado_por_inactividad', 'Cancelado por Inactividad')], default='pendiente_pago', max_length=30, verbose_name='Estado')),
                ('fecha_limite_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite para pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_entrega', models.CharField(choices=[('domicilio', 'Domicilio'), ('tienda', 'Reclamar en Tienda')], default='domicilio', max_length=20)),
                ('nombre_receptor', models.CharField(max_length=200, verbose_name='Nombre de quien recibe')),
                ('telefono_receptor', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('direccion_entrega', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Entrega')),
                ('monto_usado_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monto_pagado_verificado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Total Pagado y Verificado')),
                ('motivo_cancelacion', models.TextField(blank=True, null=True, verbose_name='Motivo de la Cancelación')),
                ('es_carrito_activo', models.BooleanField(default=False, verbose_name='¿Es carrito activo?')),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='Clientes.cliente', verbose_name='Cliente Registrado')),
                ('credito_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asociados', to='Creditos.credito')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
