# Generated by Django 5.2.1 on 2025-08-31 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedidos', '0001_initial'),
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='venta_asociada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ventas.venta', verbose_name='Venta Asociada'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='Pedidos.pedido', verbose_name='Pedido Asociado'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(condition=models.Q(('es_carrito_activo', True)), fields=('cliente', 'es_carrito_activo'), name='unique_active_cart_per_customer'),
        ),
    ]
