# Generated by Django 5.2.1 on 2025-08-31 02:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_interes_mensual_credito', models.DecimalField(decimal_places=2, default=Decimal('2.0'), help_text='Valor en porcentaje. Por ejemplo, para 2.5% ingrese 2.5', max_digits=5, verbose_name='Tasa de Interés Mensual para Créditos (%)')),
            ],
            options={
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
