# Generated by Django 5.2.1 on 2025-09-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada que aparecerá en la tienda.', verbose_name='Descripción para el Catálogo')),
                ('imagen_url', models.URLField(blank=True, help_text='Enlace a la imagen principal que se muestra en la tarjeta del catálogo.', max_length=1024, null=True, verbose_name='URL de la Imagen Principal')),
                ('peso', models.CharField(blank=True, help_text='Ej: 50 kg, 25 lbs', max_length=50, verbose_name='Peso')),
                ('dimensiones', models.CharField(blank=True, help_text='Ej: 120cm x 60cm x 15cm', max_length=100, verbose_name='Dimensiones')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Material Principal')),
                ('otros_detalles', models.TextField(blank=True, help_text='Cualquier otra especificación relevante.', verbose_name='Otros Detalles')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de Venta')),
                ('ultimo_margen_aplicado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Último Margen Aplicado (%)')),
                ('ultimo_costo_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Último Costo de Compra')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock Actual (Vendible)')),
                ('stock_minimo', models.PositiveIntegerField(default=10, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.PositiveIntegerField(default=100, verbose_name='Stock Máximo')),
                ('stock_defectuoso', models.IntegerField(default=0, verbose_name='Stock Defectuoso/No Vendible')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='Productos.categoriaproducto', verbose_name='Categoría')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='Productos.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.URLField(max_length=1024, verbose_name='URL de la Imagen Adicional')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
            },
        ),
    ]
