# Generated by Django 5.2.1 on 2025-09-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Un nombre descriptivo y legible para humanos. Ej: Crear Venta', max_length=100, verbose_name='Nombre legible del Permiso')),
                ('codename', models.CharField(help_text='El identificador único usado en el código. Ej: ventas_crear', max_length=100, unique=True, verbose_name='Codename')),
                ('modulo', models.CharField(help_text='El módulo al que pertenece este permiso. Ej: Ventas', max_length=50, verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['modulo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe un rol con este nombre. Por favor, elija un nombre diferente.'}, max_length=100, unique=True, verbose_name='Nombre del rol')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del rol')),
                ('es_protegido', models.BooleanField(default=False, help_text='Los roles protegidos no se pueden eliminar desde el panel de administración.', verbose_name='Rol Protegido')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('permisos', models.ManyToManyField(blank=True, related_name='roles', to='Roles_Permisos.permiso', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
    ]
