# Generated by Django 5.2.1 on 2025-09-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('correo', models.EmailField(error_messages={'unique': 'Un cliente con este correo electrónico ya existe. Por favor, ingrese uno diferente.'}, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT (Empresa o Persona Natural)'), ('PAS', 'Pasaporte'), ('TI', 'Tarjeta de Identidad (Menor de edad)'), ('RC', 'Registro Civil (Menor de edad NUIP)'), ('PEP', 'Permiso Especial de Permanencia'), ('PPT', 'Permiso por Protección Temporal')], max_length=3, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(error_messages={'unique': 'Un cliente con este número de documento ya existe. Por favor, verifique.'}, max_length=30, unique=True, verbose_name='Número de Documento')),
                ('es_invitado_temporal', models.BooleanField(default=False, verbose_name='¿Es cliente temporal creado desde un pedido?')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Debe cambiar contraseña')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
