# Generated by Django 5.2.1 on 2025-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('convertida', 'Convertida en Pedido'), ('vencida', 'Vencida')], default='vigente', max_length=20),
        ),
    ]
