# Generated by Django 5.2.1 on 2025-09-24 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Creditos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario_actual', models.DecimalField(decimal_places=2, help_text='Precio de venta actual del producto nuevo.', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDevuelto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario_historico', models.DecimalField(decimal_places=2, help_text='Precio al que se vendió originalmente el producto.', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(choices=[('EQUIVOCO_PRODUCTO', 'Se equivocó de producto'), ('NO_NECESITA', 'No necesita el producto'), ('PRODUCTO_DEFECTUOSO', 'Producto defectuoso')], max_length=30)),
                ('devuelto_a_proveedor', models.BooleanField(default=False, help_text='Indica si este item ya fue incluido en una devolución a proveedor.')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de la Devolución')),
                ('motivo_general', models.TextField(blank=True, null=True, verbose_name='Motivo general de la devolución')),
                ('total_productos_devueltos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_productos_cambio', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_final', models.DecimalField(decimal_places=2, default=0.0, help_text='Negativo si la empresa debe dinero, positivo si el cliente debe pagar.', max_digits=12)),
                ('tipo_reembolso', models.CharField(blank=True, choices=[('AL_CREDITO', 'Abonado al Crédito'), ('EFECTIVO', 'Reembolsado en Efectivo'), ('SIN_REEMBOLSO', 'Sin Reembolso (Cambio Exacto o a Favor)')], max_length=20)),
                ('monto_reembolsado_efectivo', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto devuelto en efectivo.', max_digits=12)),
                ('monto_abonado_credito', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto que se abonó al crédito del cliente.', max_digits=12)),
                ('monto_pagado_adicional', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto adicional pagado por el cliente.', max_digits=12)),
                ('metodo_pago_adicional', models.CharField(blank=True, choices=[('CREDITO', 'Uso de Crédito'), ('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], help_text='Método usado por el cliente para pagar la diferencia.', max_length=20, null=True)),
                ('estado_del_cambio', models.CharField(choices=[('SIN_CAMBIO', 'Sin cambio de producto'), ('MISMO_PRODUCTO', 'Cambio por el mismo producto'), ('OTRO_PRODUCTO', 'Cambio por un producto diferente')], default='SIN_CAMBIO', max_length=20)),
                ('estado', models.CharField(choices=[('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='COMPLETADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='Clientes.cliente', verbose_name='Cliente')),
                ('credito_usado_para_pago', models.ForeignKey(blank=True, help_text='Crédito usado para cubrir el balance a favor de la tienda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_pagadas', to='Creditos.credito')),
            ],
            options={
                'verbose_name': 'Devolución de Venta',
                'verbose_name_plural': 'Devoluciones de Venta',
                'ordering': ['-fecha_devolucion'],
            },
        ),
    ]
