# Generated by Django 5.2.1 on 2025-08-31 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Devoluciones', '0001_initial'),
        ('Productos', '0001_initial'),
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='venta_original',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='devolucion', to='Ventas.venta', verbose_name='Venta Original'),
        ),
        migrations.AddField(
            model_name='itemcambio',
            name='devolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_cambio', to='Devoluciones.devolucion'),
        ),
        migrations.AddField(
            model_name='itemcambio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.producto'),
        ),
        migrations.AddField(
            model_name='itemdevuelto',
            name='devolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_devueltos', to='Devoluciones.devolucion'),
        ),
        migrations.AddField(
            model_name='itemdevuelto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.producto'),
        ),
    ]
