# Generated by Django 5.2.1 on 2025-09-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creditos', '0001_initial'),
        ('Devoluciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='credito_usado_para_pago',
            field=models.ForeignKey(blank=True, help_text='Crédito usado para cubrir el balance a favor de la tienda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_pagadas', to='Creditos.credito'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='metodo_pago_adicional',
            field=models.CharField(blank=True, choices=[('CREDITO', 'Uso de Crédito'), ('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], help_text='Método usado por el cliente para pagar la diferencia.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='monto_pagado_adicional',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto adicional pagado por el cliente.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='tipo_reembolso',
            field=models.CharField(blank=True, choices=[('AL_CREDITO', 'Abonado al Crédito'), ('EFECTIVO', 'Reembolsado en Efectivo'), ('SIN_REEMBOLSO', 'Sin Reembolso (Cambio Exacto o a Favor)')], max_length=20),
        ),
    ]
