# Generated by Django 5.2.1 on 2025-09-24 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Número de factura o documento de compra proporcionado por el proveedor.', max_length=50, unique=True, verbose_name='Número de Factura del Proveedor')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='IVA (19%)')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Compra')),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de compra del proveedor')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro en Sistema')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='Proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha_compra', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto_historico', models.CharField(help_text='Nombre del producto al momento de la compra, para historial.', max_length=200, verbose_name='Nombre del producto (en compra)')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Unitario de Compra')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Compras.compra', verbose_name='Compra')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de compra',
                'verbose_name_plural': 'Ítems de compra',
            },
        ),
    ]
