# Generated by Django 5.2.1 on 2025-09-24 18:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo_aprobado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cupo Aprobado')),
                ('capital_utilizado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de las compras que el cliente ha hecho. Reduce el saldo disponible.', max_digits=12)),
                ('deuda_del_cupo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deuda principal originada por el cupo otorgado. Disminuye con los abonos.', max_digits=12)),
                ('intereses_acumulados', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de los intereses generados sobre la deuda del cupo.', max_digits=12)),
                ('tasa_interes_mensual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de Interés Mensual Aplicada (%)')),
                ('fecha_otorgamiento', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Otorgamiento')),
                ('plazo_dias', models.PositiveIntegerField(default=30, verbose_name='Plazo del Crédito (días)')),
                ('fecha_ultimo_calculo_interes', models.DateField(verbose_name='Fecha del Último Cálculo de Interés')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Pagado', 'Pagado'), ('Anulado', 'Anulado')], default='Activo', max_length=20, verbose_name='Estado del Crédito')),
                ('fecha_creacion_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_registro', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='Clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cuenta de Crédito',
                'verbose_name_plural': 'Cuentas de Crédito',
                'ordering': ['-fecha_otorgamiento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AbonoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_abono', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Abono')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto del Abono')),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pago')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_abonos/', verbose_name='Comprobante de Pago')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Verificación'), ('Verificado', 'Verificado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20, verbose_name='Estado del Abono')),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Razón por la cual el abono fue rechazado.', null=True, verbose_name='Motivo del Rechazo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='Creditos.credito', verbose_name='Cuenta de Crédito')),
            ],
            options={
                'verbose_name': 'Abono a Crédito',
                'verbose_name_plural': 'Abonos a Créditos',
                'ordering': ['-fecha_abono', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Solicitado')),
                ('plazo_dias_solicitado', models.PositiveIntegerField(default=30, verbose_name='Plazo Solicitado (días)')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Revisión'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20, verbose_name='Estado de la Solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_decision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Decisión')),
                ('motivo_decision', models.TextField(blank=True, help_text='Razón para aprobar o rechazar la solicitud.', verbose_name='Notas del Administrador')),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, help_text='Monto final aprobado por el administrador. Puede ser diferente al solicitado.', max_digits=12, null=True, verbose_name='Monto Aprobado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_credito', to='Clientes.cliente', verbose_name='Cliente')),
                ('credito_generado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='Creditos.credito', verbose_name='Crédito Generado')),
            ],
            options={
                'verbose_name': 'Solicitud de Crédito',
                'verbose_name_plural': 'Solicitudes de Crédito',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
