# Generated by Django 5.2.1 on 2025-08-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del proveedor')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía (C.C)'), ('TI', 'Tarjeta de Identidad (T.I)'), ('CE', 'Cédula de Extranjería'), ('PPT', 'Permiso por Protección Temporal'), ('Pasaporte', 'Pasaporte'), ('NIT', 'Número de Identificación Tributaria (NIT)')], max_length=20, verbose_name='Tipo de documento')),
                ('documento', models.CharField(max_length=30, unique=True, verbose_name='Número de documento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del contacto')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
