# Generated by Django 5.2.1 on 2025-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='es_empresa',
            field=models.BooleanField(default=False, verbose_name='¿Es una empresa?'),
        ),
    ]
